const List = [
    { id: 1, cId: "1", category: 'Chest', name: 'Bench Press', image: '../../../pictures/traps_files/bench press.png'},
    { id: 2, cId: "2", category: 'Shoulders', name: 'Lateral Raise', image:'../../../pictures/traps_files/barbell rows.png'},
    { id: 3, cId: "3", category: 'Chest', name: 'Incline Dumbell Press' },
    { id: 4, cId: "4", category: 'Triceps', name: 'Tricep Extension' },
    { id: 5, cId: "5", category: 'Traps', name: 'Barbell Row' },
    { id: 6, cId: "6", category: 'Lats', name: 'Lateral Pulldown' },
    { id: 7, cId: "7", category: 'Biceps', name: 'Bicep Curl' },
    { id: 8, cId: "8", category: 'Quads', name: 'Squat' },
    { id: 9, cId: "9", category: 'Hamstrings', name: 'Romanian DeadLift' },
    { id: 10, cId: "10", category: 'Quads', name: 'Leg Extension' },
    { id: 11, cId: "11", category: 'Glutes', name: 'Hip Thrust' },
    { id: 12, cId: "12", category: 'Calves', name: 'Calf Raise' },
    { id: 13, cId: "13", category: 'Abs', name: 'Crunch' },
    { id: 14, cId: "14", category: 'Forearms', name: 'Wrist Curl' },
    { id: 15, cId: "15", category: 'Shoulders', name: 'Shoulder Press' },
    { id: 16, cId: "16", category: 'Traps', name: 'Shrug' },
    { id: 17, cId: "17", category: 'Lats', name: 'Pull Up' },
    { id: 18, cId: "18", category: 'Biceps', name: 'Hammer Curl' },
    { id: 19, cId: "19", category: 'Triceps', name: 'Dips' },
    { id: 20, cId: "20", category: 'Chest', name: 'Push Up' },
    { id: 21, cId: "21", category: 'Shoulders', name: 'Reverse Fly' },
    { id: 22, cId: "22", category: 'Chest', name: 'Chest Fly' },
    { id: 23, cId: "23", category: 'Traps', name: 'Face Pull' },
    { id: 24, cId: "24", category: 'Lats', name: 'Bent Over Row' },
    { id: 25, cId: "25", category: 'Biceps', name: 'Concentration Curl' },
    { id: 26, cId: "26", category: 'Quads', name: 'Leg Press' },
    { id: 27, cId: "27", category: 'Hamstrings', name: 'Leg Curl' },
    { id: 28, cId: "28", category: 'Glutes', name: 'Glute Bridge' },
    { id: 29, cId: "29", category: 'Calves', name: 'Leg Press Calf Raise' },
    { id: 30, cId: "30", category: 'Abs', name: 'Leg Raise' },
    { id: 31, cId: "31", category: 'Forearms', name: 'Reverse Curl' },
    { id: 32, cId: "32", category: 'Shoulders', name: 'Upright Row' },
    { id: 33, cId: "33", category: 'Traps', name: 'Trap Shrug' },
    { id: 34, cId: "34", category: 'Lats', name: 'Seated Row' },
    { id: 35, cId: "35", category: 'Biceps', name: 'Preacher Curl' },
    { id: 36, cId: "36", category: 'Triceps', name: 'Skull Crusher' },
    { id: 37, cId: "37", category: 'Chest', name: 'Cable Fly' },
    { id: 38, cId: "38", category: 'Shoulders', name: 'Front Raise' },
    { id: 39, cId: "39", category: 'Chest', name: 'Dumbell Press' },
    { id: 40, cId: "40", category: 'Traps', name: 'Dumbell Row' },
    { id: 41, cId: "41", category: 'Lats', name: 'Lat Pulldown' },
    { id: 42, cId: "42", category: 'Biceps', name: 'Incline Curl' },
    { id: 43, cId: "43", category: 'Quads', name: 'Front Squat' },
    { id: 44, cId: "44", category: 'Hamstrings', name: 'Good Morning' },
    { id: 45, cId: "45", category: 'Glutes', name: 'Kickback' },
    { id: 46, cId: "46", category: 'Calves', name: 'Seated Calf Raise' },
    { id: 47, cId: "47", category: 'Abs', name: 'Plank' },
    { id: 48, cId: "48", category: 'Forearms', name: 'Reverse Wrist Curl' },
    { id: 49, cId: "49", category: 'Shoulders', name: 'Arnold Press' },
    { id: 50, cId: "50", category: 'Traps', name: 'Dumbell Shrug' },
    { id: 51, cId: "51", category: 'Lats', name: 'Straight Arm Pulldown' },
    { id: 52, cId: "52", category: 'Biceps', name: 'Drag Curl' },
    { id: 53, cId: "53", category: 'Triceps', name: 'Tricep Pushdown' },
    { id: 54, cId: "54", category: 'Chest', name: 'Pec Deck' },
    { id: 55, cId: "55", category: 'Shoulders', name: 'Lateral Raise Machine' },
    { id: 56, cId: "56", category: 'Chest', name: 'Chest Press Machine' },
    { id: 57, cId: "57", category: 'Traps', name: 'T-Bar Row' },
    { id: 58, cId: "58", category: 'Lats', name: 'Chin Up' },
    { id: 59, cId: "59", category: 'Biceps', name: 'Cable Curl' },
    { id: 60, cId: "60", category: 'Quads', name: 'Hack Squat' },
    { id: 61, cId: "61", category: 'Hamstrings', name: 'Glute Ham Raise' },
    { id: 62, cId: "62", category: 'Glutes', name: 'Hip Abduction' },
    { id: 63, cId: "63", category: 'Calves', name: 'Standing Calf Raise' },
    { id: 64, cId: "64", category: 'Abs', name: 'Russian Twist' },
    { id: 65, cId: "65", category: 'Forearms', name: 'Hammer Curl' },
    { id: 66, cId: "66", category: 'Shoulders', name: 'Reverse Pec Deck' },
    { id: 67, cId: "67", category: 'Traps', name: 'Dumbell Shrug' },
    // Add more items as needed
  ];
  
  export default List;